/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iq007_bridge_doubledummysolver_DoubleDummySolver_PlaceholderFragment */

#ifndef _Included_com_iq007_bridge_doubledummysolver_DoubleDummySolver_PlaceholderFragment
#define _Included_com_iq007_bridge_doubledummysolver_DoubleDummySolver_PlaceholderFragment
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
