/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iq007_bridge_doubledummysolver_DoubleDummySolver_BridgeWorker */

#ifndef _Included_com_iq007_bridge_doubledummysolver_DoubleDummySolver_BridgeWorker
#define _Included_com_iq007_bridge_doubledummysolver_DoubleDummySolver_BridgeWorker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iq007_bridge_doubledummysolver_DoubleDummySolver_BridgeWorker
 * Method:    SolveBoard
 * Signature: (Lcom/iq007/bridge/Deal;)I
 */
JNIEXPORT jint JNICALL Java_com_iq007_bridge_doubledummysolver_DoubleDummySolver_00024BridgeWorker_SolveBoard
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_iq007_bridge_doubledummysolver_DoubleDummySolver_BridgeWorker
 * Method:    CalcDDtablePBN
 * Signature: (Ljava/lang/String;)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_iq007_bridge_doubledummysolver_DoubleDummySolver_00024BridgeWorker_CalcDDtablePBN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_iq007_bridge_doubledummysolver_DoubleDummySolver_BridgeWorker
 * Method:    CalcParPBN
 * Signature: (Ljava/lang/String;I)[[C
 */
JNIEXPORT jobjectArray JNICALL Java_com_iq007_bridge_doubledummysolver_DoubleDummySolver_00024BridgeWorker_CalcParPBN
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
