/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iq007_bridge_doubledummysolver_DoubleDummySolver_PlaceholderFragment */

#ifndef _Included_com_iq007_bridge_doubledummysolver_DoubleDummySolver_PlaceholderFragment
#define _Included_com_iq007_bridge_doubledummysolver_DoubleDummySolver_PlaceholderFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iq007_bridge_doubledummysolver_DoubleDummySolver_PlaceholderFragment
 * Method:    SolveBoard
 * Signature: (Lcom/iq007/bridge/Deal;)I
 */
JNIEXPORT jint JNICALL Java_com_iq007_bridge_doubledummysolver_DoubleDummySolver_00024PlaceholderFragment_SolveBoard
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
