/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_iq007_bridge_doubledummysolver_DoubleDummySolver.h"
/* Header for class com_iq007_bridge_doubledummysolver_DoubleDummySolver */

extern "C"
{
/*
 * Class:     com_iq007_bridge_doubledummysolver_DoubleDummySolver
 * Method:    SolveBoard
 * Signature: (Lcom/iq007/bridge/Deal;)I
 */
JNIEXPORT jint JNICALL Java_com_iq007_bridge_doubledummysolver_DoubleDummySolver_SolveBoard
  (JNIEnv * env, jobject deal, jobject deal2)
  {

        return 5;

  }

}